### PR TITLE
Bluetooth adapter

### PR DESCRIPTION
**Pull request by sloboste**
I think this is ready for some feedback. Please note that the classes and enums in the `gatt` file get cleaned up a later commit but it is pretty messy early on.

The purpose of this PR was to:
1) Start refactoring pygatt to be a BluetoothAdapter that spins off BleDevice instances
2) Start refactoring the BGAPI backend to fit this new abstraction
3) Begin some cleanup of the BGAPI backend

I see the next steps as:
1) Incorporate changes from your feedback into this PR
2) Incorporate changes from the logging optimization PR that @peplin merged recently

Note:
In some of the TODOs you'll see a `connection` object referenced. What I was thinking is that since the dongle sends back a lot of packets that pertain to a specific connection handle, we could encapsulate the connection state in an object which would clean up the code a bit as well as bring us a step closer to supporting multiple connections simultaneously on the dongle (the BLED112 can support multiple but I forgot how many at a time).

I'm going to work on using the BluetoothAdapter with some of our existing code while this is being reviewed.

Also, on a side note, we ought to get rid of the Python 2.6 build that travis does because I think we are using features that aren't supported on 2.6 so it always fails.

### CODE REVIEW

**Comment by sloboste** [comment]
Oh and I didn't have time to refactor the GATTTool backend so that is a next step as well

**Comment by peplin** [comment]
Wow! At first glance, I think your design approach is solid. This PR is a bit hard for me to grok because of the size and because it doesn't replace any of the existing code - it's just 4200 new lines of code. I think a good next step would be to delete the other implementation and drop the new one in its place, then I can tell what is being replaced (and what is truly being added). As it is now, 4200 lines of code seems like way too much just to have a nicer API for querying the RSSI (among other things), but I know the true additions are less than that.

**Comment by sloboste** [comment]
Also, I think you're looking at it the wrong way. It's not just an API change to make programming a bit easier for me right here and now, it's an investment that does have an upfront cost but also a payoff that is worth it long term. There are other problems that I think this will help solve in the near future as well, but this isn't a good place to mention them.

**Comment by peplin** [comment]
Closing in favor of the more limited refactor in ampledata/pygatt#2

**Pull request closed without merging**
